### ISSUE TITLE
Request: Add a way to retry / resume transfers if a failure occurs

### ISSUE THREAD

**Issue by ageisen2000** [sigma67/spotify_to_ytmusic#69] opened 2023-08-24 01:31 UTC
A failure occurred during a transfer of my liked playlist to youtube music. I am not sure if it's because I'm being rate limited or something else.

There should be a way to resume previously failed transfers.

**Comment by sigma67** [comment] 2023-08-24 07:25
there is already WIP that enables this, see here: https://github.com/sigma67/spotify_to_ytmusic/pull/53

**Comment by sigma67** [comment] 2024-01-22 11:49
Duplicate of #39

**Closed by sigma67** 2024-01-22 11:49 UTC
