### ISSUE TITLE
Google OAuth not working

### ISSUE THREAD

**Issue by Rexadev** [sigma67/spotify_to_ytmusic#62] opened 2023-06-06 07:54 UTC

**Comment by sigma67** [comment] 2023-06-06 09:13
Well, did you try again?

**Comment by Rexadev** [comment] 2023-06-06 09:48
> Well, did you try again?

Yes 7 times

**Comment by z3t4m4n** [comment] 2023-07-31 08:05
Hi, 
same issue.
I placed a try/except on /home/$HOME/.local/lib/python3.11/site-packages/ytmusicapi/auth/oauth.py
( ytmusicapi 1.1.1):
```
    def _parse_token(response) -> Dict:                                                                                                                 
        try:                                                                                                                                            
            token = response.json()                                                                                                                     
            token["expires_at"] = int(time.time()) + int(token["expires_in"])                                                                           
        except Exception as error:                                                                                                                      
            print("An error occurred:", type(error).__name__) # An error occurred: NameError                                                            
            print(response.json())                                                                                                                      
        return token 
```

```
$ spotify_to_ytmusic setup                                                                                                            
Choose which API to set up                                                                                                                              
(1) Spotify                                                                                                                                             
(2) YouTube                                                                                                                                             
(3) both                                                                                                                                                
2                                                                                                                                                       
Go to https://www.google.com/device?user_code=XXXX-XXXX, finish the login flow and press Enter when done, Ctrl-C to abort
<Response [400]>                                                                                                                                        
An error occurred: KeyError                                                                                                                             
{'error': 'invalid_request', 'error_description': 'Credentials in post body and basic Authorization header do not match'}                               
<Response [400]>  
```
My google account has more than 1 youtube account linked, maybe it is related to that.

**Comment by LouisHrg** [comment] 2023-08-08 20:40
Hi, same issue with all my accounts, nothing is working atm

**Comment by sigma67** [comment] 2023-08-29 12:43
@LouisHrg do you also have more than 1 YouTube account linked to your Google account?

**Comment by Rexadev** [comment] 2023-08-29 17:10
> @LouisHrg do you also have more than 1 YouTube account linked to your Google account?

Is that possible @sigma67

**Comment by z3t4m4n** [comment] 2023-08-29 17:28
In my case, at one time you could have a YouTube account; before it was purchased by google.
Later when they purchased and merged YouTube into the google ecosystem, you got to keep the old YouTube account if you wanted, and many did as its not wise to be commenting in YouTube with your real name, and keeping your old channel/uploads,
So some people have more than one distinct YouTube accounts nested in a single google account.

**Comment by knedl1k** [comment] 2023-10-30 21:08
Yeah same error here. Even if I do not use the OAuth method for private playlists I cannot log into the YT.
![image](https://github.com/sigma67/spotify_to_ytmusic/assets/94710787/eca22800-e504-4dc0-bd58-aa7784016dd8)

**Comment by sigma67** [comment] 2023-10-31 07:08
Hi guys, I'm sorry that this is not working for you. This issue is account bound, so I'm unfortunately unable to help in this case.

Feel free to debug this further, the issue is probably related to the oauth functionality in ytmusicapi: https://github.com/sigma67/ytmusicapi/blob/master/ytmusicapi/auth/oauth.py

Check also here for more on how it works behind the scenes: https://github.com/sigma67/ytmusicapi/issues/10#issuecomment-1482498341

Perhaps you can find the issue by debugging with your account on the YouTube TV interface

**Comment by Rexadev** [comment] 2023-10-31 11:03
@LouisHrg @z3t4m4n @knedl1k  Try https://github.com/yogeshwaran01/spotify-playlist-to-youtube-playlist

**Comment by sigma67** [comment] 2024-01-22 11:51
This issue is too broad and there is no clear error cause, therefore I'm closing it

If you're having issues with oauth you can also use browser auth: https://ytmusicapi.readthedocs.io/en/stable/setup/index.html

The settings file to edit is at `%APPDATA%\spotify_to_ytmusic` on Windows, in `~/.cache` on Linux

**Closed by sigma67** 2024-01-22 11:51 UTC

**Comment by Daniel-GabrielN** [comment] 2024-08-31 10:17
I have encountered the same issue and solved it by deleting the second channel and then pasting the link ``https://www.google.com/device?user_code=XXXX-XXXX`` into a private window.

**Comment by kissu** [comment] 2024-11-14 14:52
> This issue is too broad and there is no clear error cause, therefore I'm closing it
> 
> If you're having issues with oauth you can also use browser auth: [ytmusicapi.readthedocs.io/en/stable/setup/index.html](https://ytmusicapi.readthedocs.io/en/stable/setup/index.html)
> 
> The settings file to edit is at `%APPDATA%\spotify_to_ytmusic` on Windows, in `~/.cache` on Linux

what about MacOS here?
