### ISSUE TITLE
OAuth not redirecting to localhost

### ISSUE THREAD

**Issue by SCLeoo** [sigma67/spotify_to_ytmusic#81] opened 2023-12-21 20:29 UTC
So the main porpuse of using this handy project is to transfer my liked songs into a playlist on YTMusic, I transferred mine with no problems at all, but now that I'm migrating my gfs liked songs I'm unable to run the commands succesfully beacause when I go to OAuth and finalize the setup, I'm not being redirected to localhost, therefore, I'm unable to sign in through the project and I'm getting this errors:

![image](https://github.com/sigma67/spotify_to_ytmusic/assets/31389063/a8918458-59e3-4e1f-928a-2af19ed75c81)

I know maybe it's not a code issue but still, wanted to see if there is something I'm not seeing right here.

Thanks in advance and congrats on building something so useful for free :)

**Comment by sigma67** [comment] 2024-01-22 11:47
Duplicate of #85

**Closed by sigma67** 2024-01-22 11:47 UTC
